import { ProductType } from "@/types/ProductType";
import { Timestamp } from "firebase/firestore";

const defaultProductData: ProductType = {
  id: "",
  productTitle: "",
  productSubtitle: "",
  slug: "",
  permalink: "",
  type: "simple",
  status: "draft",
  featured: false,
  catalog_visibility: "visible",
  shortDescription: "",
  sku: "",
  price: "",
  regularPrice: "",
  salePrice: "",
  gstRate: "",
  guides: [],
  height: 0,
  length: 0,
  breadth: 0,
  weight: 0,
  isReadyToWear: false,
  readyToWearCharges: 0,
  isPrePlated: false,
  prePlatedCharges: 0,
  isReturn: true,
  returnPeriod: "Hassle-free 10 days return & exchange",
  isShippingCharge: false,
  deliveryTimePeriod: "2-7 days delivery within India",
  isCashOnDelivery: true,
  HSN: "",
  createdAt: Timestamp.now(),
  ModifiedAt: Timestamp.now(),
  dateOnSaleTo: null,
  dateOnSaleFrom: null,
  price_html: "",
  onSale: false,
  purchaseSale: false,
  totalSales: 0,
  manageStatus: false,
  stockQuantity: 0,
  stockStatus: "in-stock",
  backorders: false,
  backordersAllowed: false,
  shipping_taxable: "",
  reviewsAllowed: true,
  averageRating: "0",
  ratingCount: 0,
  categories: [],
  tags: [],
  featuredImage: "",
  galleryImages: [],
  videoUrl: "",
  variationProduct: [],
  attributes: [],
  menuOrder: 0,
  metaData: [],
  description: [
    { heading: "Details", content: "" },
    { heading: "Description", content: "" },
    { heading: "Shipping", content: "" },
    { heading: "Return & Exchange", content: "" },
    { heading: "Manufacturing Information", content: "" },
    { heading: "Support", content: "" },
  ],
};

export default defaultProductData;